name: Canonical action-tmate test
    
on:
  push:
    
jobs:
  build:
    runs-on: [self-hosted, linux, X64, jammy, large]
    steps:
    - name: Setup tmate session
      uses: canonical/action-tmate@main
      with:
        detached: true
